import {apis} from '../../permission-init/utils';

const permissions = [
  {
    permissionKey: 'Recharge_Compensation_CS',
    remark: 'Recharge Compensation',
    name: 'Recharge Compensation CS',
    resourceKeyList: [
      'DEPOSIT_WITHDRAWAL',
      'DEPOSIT_WITHDRAWAL.RECHARGE_COMPENSATION_LIST',
      'DEPOSIT_WITHDRAWAL.RECHARGE_COMPENSATION_LIST.CHECK',
      'DEPOSIT_WITHDRAWAL.RECHARGE_COMPENSATION_LIST.APPLY',
      'DEPOSIT_WITHDRAWAL.RECHARGE_COMPENSATION_LIST.ADD',
      'DEPOSIT_WITHDRAWAL.RECHARGE_COMPENSATION_LIST.DELETE',
      'DEPOSIT_WITHDRAWAL.RECHARGE_COMPENSATION_LIST.LIST',
    ],
  },
  {
    permissionKey: 'Recharge_Compensation_Tech',
    remark: 'Recharge Compensation',
    name: 'Recharge Compensation Tech',
    resourceKeyList: [
      'DEPOSIT_WITHDRAWAL',
      'DEPOSIT_WITHDRAWAL.RECHARGE_COMPENSATION_LIST',
      'DEPOSIT_WITHDRAWAL.RECHARGE_COMPENSATION_LIST.ADD',
      'DEPOSIT_WITHDRAWAL.RECHARGE_COMPENSATION_LIST.CHECK',
      'DEPOSIT_WITHDRAWAL.RECHARGE_COMPENSATION_LIST.APPLY',
      'DEPOSIT_WITHDRAWAL.RECHARGE_COMPENSATION_LIST.DELETE',
      'DEPOSIT_WITHDRAWAL.RECHARGE_COMPENSATION_LIST.CHECK_APPROVE',
      'DEPOSIT_WITHDRAWAL.RECHARGE_COMPENSATION_LIST.CHECK_REJECT',
      'DEPOSIT_WITHDRAWAL.RECHARGE_COMPENSATION_LIST.APPROVE',
      'DEPOSIT_WITHDRAWAL.RECHARGE_COMPENSATION_LIST.REJECT',
      'DEPOSIT_WITHDRAWAL.RECHARGE_COMPENSATION_LIST.LIST',
    ],
  },
  {
    permissionKey: 'Recharge_Compensation_OP',
    remark: 'Recharge Compensation',
    name: 'Recharge Compensation OP',
    resourceKeyList: [
      'DEPOSIT_WITHDRAWAL',
      'DEPOSIT_WITHDRAWAL.RECHARGE_COMPENSATION_LIST',
      'DEPOSIT_WITHDRAWAL.RECHARGE_COMPENSATION_LIST.APPROVE',
      'DEPOSIT_WITHDRAWAL.RECHARGE_COMPENSATION_LIST.REJECT',
      'DEPOSIT_WITHDRAWAL.RECHARGE_COMPENSATION_LIST.LIST',
    ],
  },
];

export async function handleInitPermissions() {
  for (let i = 0; i < permissions.length; i++) {
    await apis.addPermission(permissions[i]);
  }
}
