const data = [
  {
    id: 38,
    username: 'weili',
    mobile: '1553807970',
    email: 'weili.pei@cmexpro.com',
    status: 1,
    roleInfoList: [
      {
        id: 11,
        name: 'global Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 1,
        name: 'Super Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 148,
        name: 'Maker_Whitelist',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 149,
        name: 'Add',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 150,
        name: 'Edit',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 138,
        name: '[TR] ADMIN',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 139,
        name: '[TR] All View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 107,
        name: 'Agent_Audit',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
    ],
    enable2faKey: true,
    google2faSecret: '',
    createdAt: 1593580493000,
    updatedAt: 1665364075000,
  },
  {
    id: 213,
    username: 'ivan.qin',
    mobile: '',
    email: 'ivan.qin@phemex.com',
    status: 1,
    roleInfoList: [
      {
        id: 1,
        name: 'Super Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 29,
        name: 'Referral_Program',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 16,
        name: 'BD_ADMIN',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 97,
        name: 'Spot_VIP_List',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 95,
        name: 'Spot_VIP_Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 115,
        name: 'BD_Header',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 3,
        name: 'bd member',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 123,
        name: 'Privilege_Center',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 32,
        name: 'op airdrop audit',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 138,
        name: '[TR] ADMIN',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 139,
        name: '[TR] All View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 140,
        name: '[TR] Deposit Approve',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 107,
        name: 'Agent_Audit',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 142,
        name: 'QA',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 36,
        name: 'EmailManagement',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 50,
        name: 'Operation_Email',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 49,
        name: 'Operation_Email_Create',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 48,
        name: 'Operation_Email_Edit',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 45,
        name: 'Operation_Email_View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
    ],
    enable2faKey: true,
    google2faSecret: '',
    createdAt: 1647278848000,
    updatedAt: 1665358308000,
  },
  {
    id: 327,
    username: 'abel.sohajda@phemex.com',
    mobile: null,
    email: 'abel.sohajda@phemex.com',
    status: 0,
    roleInfoList: [
      {
        id: 138,
        name: '[TR] ADMIN',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 139,
        name: '[TR] All View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 140,
        name: '[TR] Deposit Approve',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 3,
        name: 'bd member',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 116,
        name: 'BD_Country_Manager',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 50,
        name: 'Operation_Email',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 49,
        name: 'Operation_Email_Create',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 48,
        name: 'Operation_Email_Edit',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 36,
        name: 'EmailManagement',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
    ],
    enable2faKey: true,
    google2faSecret: '',
    createdAt: 1662080961000,
    updatedAt: 1664414293000,
  },
  {
    id: 310,
    username: 'translator.tr',
    mobile: null,
    email: 'translator.tr@phemex.com',
    status: 0,
    roleInfoList: [
      {
        id: 1,
        name: 'Super Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 108,
        name: 'Announcement_Management_Edit',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 109,
        name: 'Announcement_Management_Create',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 47,
        name: 'Announcement_Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 37,
        name: 'BannerManagement',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 138,
        name: '[TR] ADMIN',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 164,
        name: '[TR] All Edit',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 139,
        name: '[TR] All View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
    ],
    enable2faKey: true,
    google2faSecret: '',
    createdAt: 1658442364000,
    updatedAt: 1664162728000,
  },
  {
    id: 323,
    username: 'benny.chen@phemex.com',
    mobile: null,
    email: 'benny.chen@phemex.com',
    status: 0,
    roleInfoList: [
      {
        id: 2,
        name: 'cs member',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 20,
        name: 'cs bonus issue',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 21,
        name: 'cs big client',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 13,
        name: 'CS_Deposit_Withdraw',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 1,
        name: 'Super Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 59,
        name: 'P2P Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 73,
        name: 'P2P_Order_List',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 120,
        name: 'Personal KYC Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 8,
        name: 'ban user',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 138,
        name: '[TR] ADMIN',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 164,
        name: '[TR] All Edit',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 139,
        name: '[TR] All View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 140,
        name: '[TR] Deposit Approve',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
    ],
    enable2faKey: true,
    google2faSecret: '',
    createdAt: 1661717650000,
    updatedAt: 1664146985000,
  },
  {
    id: 308,
    username: 'tugce',
    mobile: null,
    email: 'tugce@phemex.com',
    status: 0,
    roleInfoList: [
      {
        id: 1,
        name: 'Super Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 108,
        name: 'Announcement_Management_Edit',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 109,
        name: 'Announcement_Management_Create',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 47,
        name: 'Announcement_Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 37,
        name: 'BannerManagement',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 3,
        name: 'bd member',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 48,
        name: 'Operation_Email_Edit',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 49,
        name: 'Operation_Email_Create',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 50,
        name: 'Operation_Email',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 45,
        name: 'Operation_Email_View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 77,
        name: 'Airdrop_List',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 35,
        name: 'ContentManagement',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 138,
        name: '[TR] ADMIN',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 164,
        name: '[TR] All Edit',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 139,
        name: '[TR] All View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
    ],
    enable2faKey: true,
    google2faSecret: '',
    createdAt: 1658123831000,
    updatedAt: 1663901698000,
  },
  {
    id: 109,
    username: 'kathy',
    mobile: '',
    email: 'kathy.liu@phemex.com',
    status: 1,
    roleInfoList: [
      {
        id: 2,
        name: 'cs member',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 27,
        name: 'cs-security',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 120,
        name: 'Personal KYC Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 147,
        name: 'Deposit Slip Approve',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 139,
        name: '[TR] All View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 140,
        name: '[TR] Deposit Approve',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 1,
        name: 'Super Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 43,
        name: 'Withdrawal_Request',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
    ],
    enable2faKey: true,
    google2faSecret: '',
    createdAt: 1623366527000,
    updatedAt: 1663712547000,
  },
  {
    id: 256,
    username: 'eleven',
    mobile: '',
    email: 'eleven@phemex.com',
    status: 1,
    roleInfoList: [
      {
        id: 37,
        name: 'BannerManagement',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 35,
        name: 'ContentManagement',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 1,
        name: 'Super Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 98,
        name: 'Guess_Price',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 3,
        name: 'bd member',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 32,
        name: 'op airdrop audit',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 77,
        name: 'Airdrop_List',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 50,
        name: 'Operation_Email',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 49,
        name: 'Operation_Email_Create',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 48,
        name: 'Operation_Email_Edit',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 45,
        name: 'Operation_Email_View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 123,
        name: 'Privilege_Center',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 136,
        name: 'Active_Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 124,
        name: 'Privilege_Center_View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 42,
        name: 'Deposit_And_Withdrawal',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 57,
        name: 'Tool_Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 138,
        name: '[TR] ADMIN',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 164,
        name: '[TR] All Edit',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 139,
        name: '[TR] All View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
    ],
    enable2faKey: true,
    google2faSecret: '',
    createdAt: 1652932795000,
    updatedAt: 1663641938000,
  },
  {
    id: 204,
    username: 'miya',
    mobile: '',
    email: 'miya@phemex.com',
    status: 1,
    roleInfoList: [
      {
        id: 98,
        name: 'Guess_Price',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 161,
        name: 'KOL_User_Data',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 162,
        name: 'Register Config',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 159,
        name: 'Online/Offline',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 158,
        name: 'Add/Edit',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 6,
        name: 'op member',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 3,
        name: 'bd member',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 36,
        name: 'EmailManagement',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 1,
        name: 'Super Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 50,
        name: 'Operation_Email',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 102,
        name: 'App_Function_Module',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 113,
        name: 'Internal_Conversion_List',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 123,
        name: 'Privilege_Center',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 129,
        name: 'Ranking_Sham',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 142,
        name: 'QA',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 125,
        name: 'App_Edition_Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 69,
        name: 'IP_Whitelist',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 145,
        name: 'Official_Verify',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 146,
        name: 'Official_Verify_Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 56,
        name: 'Operation_Activity',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 160,
        name: 'KOL_User_Data_List',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 156,
        name: 'KOL_Activity_Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 155,
        name: 'KOL_Activity_Create',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 138,
        name: '[TR] ADMIN',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 164,
        name: '[TR] All Edit',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 139,
        name: '[TR] All View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 140,
        name: '[TR] Deposit Approve',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
    ],
    enable2faKey: true,
    google2faSecret: '',
    createdAt: 1646625953000,
    updatedAt: 1663640595000,
  },
  {
    id: 115,
    username: 'ge.sun',
    mobile: '13515121288',
    email: 'ge.sun@cmexpro.com',
    status: 1,
    roleInfoList: [
      {
        id: 90,
        name: 'Coin_Info',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 89,
        name: 'Coin_Basic_Info',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 88,
        name: 'Category_List',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 87,
        name: 'Category_Info',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 84,
        name: 'Contract_Pair_Configuration',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 83,
        name: 'Contract_Pair_Detail',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 113,
        name: 'Internal_Conversion_List',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 91,
        name: 'Coin_Configuration',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 1,
        name: 'Super Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 81,
        name: 'Convert_Configuration',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 43,
        name: 'Withdrawal_Request',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 106,
        name: 'AML_Whitelist',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 105,
        name: 'AML_Blacklist',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 51,
        name: 'Deposit_Slip_Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 95,
        name: 'Spot_VIP_Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 111,
        name: 'Contract_Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 112,
        name: 'Trade_Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 114,
        name: 'User_Positions',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 44,
        name: 'User_List',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 62,
        name: 'User_Detail',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 61,
        name: 'User_Activity_Log',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 138,
        name: '[TR] ADMIN',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 118,
        name: 'Tech_Data_Science',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 122,
        name: 'Tech_Science_Admin_Quality',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 82,
        name: 'Base_Configuration',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 85,
        name: 'Spot_Pair_Detail',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 86,
        name: 'Spot_Pair_Configuration',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 143,
        name: 'Spot Fee Promotion',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 164,
        name: '[TR] All Edit',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 139,
        name: '[TR] All View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 140,
        name: '[TR] Deposit Approve',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
    ],
    enable2faKey: true,
    google2faSecret: '',
    createdAt: 1625527247000,
    updatedAt: 1663640583000,
  },
  {
    id: 313,
    username: 'eric.he',
    mobile: null,
    email: 'eric.he@cmexpro.com',
    status: 0,
    roleInfoList: [
      {
        id: 1,
        name: 'Super Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 123,
        name: 'Privilege_Center',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 36,
        name: 'EmailManagement',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 134,
        name: 'System_Email_Create',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 135,
        name: 'System_Email_Release',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 142,
        name: 'QA',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 138,
        name: '[TR] ADMIN',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 139,
        name: '[TR] All View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 140,
        name: '[TR] Deposit Approve',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 164,
        name: '[TR] All Edit',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
    ],
    enable2faKey: true,
    google2faSecret: '',
    createdAt: 1659485153000,
    updatedAt: 1663640571000,
  },
  {
    id: 148,
    username: 'baolong.hou',
    mobile: '',
    email: 'baolong.hou@cmexpro.com',
    status: 1,
    roleInfoList: [
      {
        id: 1,
        name: 'Super Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 11,
        name: 'global Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 12,
        name: 'system Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 58,
        name: 'tech p2p',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 118,
        name: 'Tech_Data_Science',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 120,
        name: 'Personal KYC Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 138,
        name: '[TR] ADMIN',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 141,
        name: 'User Detail Contract Fee Edit&Reset',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 143,
        name: 'Spot Fee Promotion',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 146,
        name: 'Official_Verify_Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 147,
        name: 'Deposit Slip Approve',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 151,
        name: 'Fiat_Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 163,
        name: 'KYC Withdrawal Limit',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
    ],
    enable2faKey: true,
    google2faSecret: '',
    createdAt: 1634685353000,
    updatedAt: 1663282483000,
  },
  {
    id: 67,
    username: 'mike',
    mobile: '',
    email: 'mike.yu@phemex.com',
    status: 1,
    roleInfoList: [
      {
        id: 2,
        name: 'cs member',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 8,
        name: 'ban user',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 24,
        name: 'customize_mike_liu',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 27,
        name: 'cs-security',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 120,
        name: 'Personal KYC Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 139,
        name: '[TR] All View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 140,
        name: '[TR] Deposit Approve',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 1,
        name: 'Super Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 79,
        name: 'p2p-cs',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 147,
        name: 'Deposit Slip Approve',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 43,
        name: 'Withdrawal_Request',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 105,
        name: 'AML_Blacklist',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
    ],
    enable2faKey: true,
    google2faSecret: '',
    createdAt: 1609291427000,
    updatedAt: 1663205031000,
  },
  {
    id: 138,
    username: 'mengdan.zhou',
    mobile: '',
    email: 'mengdan.zhou@cmexpro.com',
    status: 1,
    roleInfoList: [
      {
        id: 5,
        name: 'rd member',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 40,
        name: 'User_Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 44,
        name: 'User_List',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 62,
        name: 'User_Detail',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 138,
        name: '[TR] ADMIN',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 139,
        name: '[TR] All View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 140,
        name: '[TR] Deposit Approve',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
    ],
    enable2faKey: true,
    google2faSecret: '',
    createdAt: 1632622754000,
    updatedAt: 1663130611000,
  },
  {
    id: 5,
    username: 'junshai.yang',
    mobile: '17601386118',
    email: 'junshuai.yang@cmexpro.com',
    status: 1,
    roleInfoList: [
      {
        id: 95,
        name: 'Spot_VIP_Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 72,
        name: 'Ban_Approval',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 71,
        name: 'NewPremiun',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 70,
        name: 'Discount_User_List',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 69,
        name: 'IP_Whitelist',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 68,
        name: 'Feedback',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 67,
        name: 'Record_Tracking',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 66,
        name: 'OTC_History',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 65,
        name: 'Reset_2FA_Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 63,
        name: 'Enterprise_KYC',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 62,
        name: 'User_Detail',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 61,
        name: 'User_Activity_Log',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 60,
        name: 'Enterprise_Kyc_Edit',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 55,
        name: 'Premium_List',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 54,
        name: 'Big_Client_Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 44,
        name: 'User_List',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 39,
        name: 'tech permissions',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 58,
        name: 'tech p2p',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 22,
        name: 'tech member',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 25,
        name: 'tech coin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 1,
        name: 'Super Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 11,
        name: 'global Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 12,
        name: 'system Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 94,
        name: 'Withdrawal_error_audit',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 93,
        name: 'withdrawal error apply',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 138,
        name: '[TR] ADMIN',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 139,
        name: '[TR] All View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 140,
        name: '[TR] Deposit Approve',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 32,
        name: 'op airdrop audit',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 126,
        name: 'Risk Manage Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 128,
        name: 'Risk Manage View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 127,
        name: 'Risk Manage Edit',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 123,
        name: 'Privilege_Center',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 136,
        name: 'Active_Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 124,
        name: 'Privilege_Center_View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 118,
        name: 'Tech_Data_Science',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 122,
        name: 'Tech_Science_Admin_Quality',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 111,
        name: 'Contract_Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 132,
        name: 'Trader_Announcement',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 112,
        name: 'Trade_Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 77,
        name: 'Airdrop_List',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 53,
        name: 'Withdrawal_White_List',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 52,
        name: 'Withdrawal_Address_List',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 51,
        name: 'Deposit_Slip_Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 43,
        name: 'Withdrawal_Request',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 59,
        name: 'P2P Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 73,
        name: 'P2P_Order_List',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 57,
        name: 'Tool_Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 56,
        name: 'Operation_Activity',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 98,
        name: 'Guess_Price',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 133,
        name: 'Sorting_Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 131,
        name: 'Tag_Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 41,
        name: 'Financial_Reconciliation',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 130,
        name: 'Savings_Product_Setting',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 75,
        name: 'Exclusive_Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 74,
        name: 'Financial_Dashboard',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 40,
        name: 'User_Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 141,
        name: 'User Detail Contract Fee Edit&Reset',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 120,
        name: 'Personal KYC Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 97,
        name: 'Spot_VIP_List',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 114,
        name: 'User_Positions',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 82,
        name: 'Base_Configuration',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 113,
        name: 'Internal_Conversion_List',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 91,
        name: 'Coin_Configuration',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 90,
        name: 'Coin_Info',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 89,
        name: 'Coin_Basic_Info',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 88,
        name: 'Category_List',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 87,
        name: 'Category_Info',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 86,
        name: 'Spot_Pair_Configuration',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 85,
        name: 'Spot_Pair_Detail',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 84,
        name: 'Contract_Pair_Configuration',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 83,
        name: 'Contract_Pair_Detail',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 80,
        name: 'Convert_Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 92,
        name: 'Convert_Dashboard',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 81,
        name: 'Convert_Configuration',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 42,
        name: 'Deposit_And_Withdrawal',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 106,
        name: 'AML_Whitelist',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 105,
        name: 'AML_Blacklist',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 101,
        name: 'User_Recharge_Compensation_List',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 99,
        name: 'User_Recharge_Compensation_Add',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 30,
        name: 'customize_adriano_yang',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 29,
        name: 'Referral_Program',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 137,
        name: 'Personal_Program',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 129,
        name: 'Ranking_Sham',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 119,
        name: 'Invite_Ban',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 107,
        name: 'Agent_Audit',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 104,
        name: 'Agent_List',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 103,
        name: 'Agent_Details',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 142,
        name: 'QA',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 144,
        name: 'Predict_Configuration',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 143,
        name: 'Spot Fee Promotion',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 147,
        name: 'Deposit Slip Approve',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 148,
        name: 'Maker_Whitelist',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 153,
        name: 'Contract_Fee_Upload',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 26,
        name: 'tech_airdrop_query',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 38,
        name: 'tech deposit withdrawal manage',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 35,
        name: 'ContentManagement',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 135,
        name: 'System_Email_Release',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 134,
        name: 'System_Email_Create',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 125,
        name: 'App_Edition_Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 109,
        name: 'Announcement_Management_Create',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 108,
        name: 'Announcement_Management_Edit',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 102,
        name: 'App_Function_Module',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 50,
        name: 'Operation_Email',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 49,
        name: 'Operation_Email_Create',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 48,
        name: 'Operation_Email_Edit',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 47,
        name: 'Announcement_Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 46,
        name: 'Promotions_Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 45,
        name: 'Operation_Email_View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 37,
        name: 'BannerManagement',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 36,
        name: 'EmailManagement',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 33,
        name: 'SuperAdmin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 34,
        name: 'tech robot account transfer',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 31,
        name: 'Basic admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 145,
        name: 'Official_Verify',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 146,
        name: 'Official_Verify_Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
    ],
    enable2faKey: true,
    google2faSecret: '',
    createdAt: 1580777387000,
    updatedAt: 1663121333000,
  },
  {
    id: 329,
    username: 'nick@phemex.com',
    mobile: null,
    email: 'nick@phemex.com',
    status: 0,
    roleInfoList: [
      {
        id: 1,
        name: 'Super Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 142,
        name: 'QA',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 2,
        name: 'cs member',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 121,
        name: 'USER_LIST_AND_DETAILS_CS',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 79,
        name: 'p2p-cs',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 27,
        name: 'cs-security',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 42,
        name: 'Deposit_And_Withdrawal',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 43,
        name: 'Withdrawal_Request',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 44,
        name: 'User_List',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 62,
        name: 'User_Detail',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 33,
        name: 'SuperAdmin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 21,
        name: 'cs big client',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 20,
        name: 'cs bonus issue',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 138,
        name: '[TR] ADMIN',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 139,
        name: '[TR] All View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 140,
        name: '[TR] Deposit Approve',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
    ],
    enable2faKey: true,
    google2faSecret: '',
    createdAt: 1662488904000,
    updatedAt: 1663120292000,
  },
  {
    id: 159,
    username: 'omer.anahtar@phemex.com',
    mobile: '',
    email: 'omer.anahtar@phemex.com',
    status: 1,
    roleInfoList: [
      {
        id: 2,
        name: 'cs member',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 13,
        name: 'CS_Deposit_Withdraw',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 59,
        name: 'P2P Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 73,
        name: 'P2P_Order_List',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 1,
        name: 'Super Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 139,
        name: '[TR] All View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 140,
        name: '[TR] Deposit Approve',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 120,
        name: 'Personal KYC Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
    ],
    enable2faKey: true,
    google2faSecret: '',
    createdAt: 1638726665000,
    updatedAt: 1663090755000,
  },
  {
    id: 166,
    username: 'jesslyn.tang@phemex.com',
    mobile: '',
    email: 'jesslyn.tang@phemex.com',
    status: 1,
    roleInfoList: [
      {
        id: 2,
        name: 'cs member',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 27,
        name: 'cs-security',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 43,
        name: 'Withdrawal_Request',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 1,
        name: 'Super Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 139,
        name: '[TR] All View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 140,
        name: '[TR] Deposit Approve',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 147,
        name: 'Deposit Slip Approve',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
    ],
    enable2faKey: true,
    google2faSecret: '',
    createdAt: 1639098375000,
    updatedAt: 1662685888000,
  },
  {
    id: 140,
    username: 'vishaldeep.singh',
    mobile: '',
    email: 'vishaldeep.singh@phemex.com',
    status: 1,
    roleInfoList: [
      {
        id: 2,
        name: 'cs member',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 1,
        name: 'Super Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 139,
        name: '[TR] All View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 140,
        name: '[TR] Deposit Approve',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 43,
        name: 'Withdrawal_Request',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
    ],
    enable2faKey: true,
    google2faSecret: '',
    createdAt: 1633545358000,
    updatedAt: 1662595710000,
  },
  {
    id: 134,
    username: 'deepak.girdhar',
    mobile: '',
    email: 'deepak.girdhar@phemex.com',
    status: 1,
    roleInfoList: [
      {
        id: 2,
        name: 'cs member',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 1,
        name: 'Super Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 139,
        name: '[TR] All View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 140,
        name: '[TR] Deposit Approve',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 43,
        name: 'Withdrawal_Request',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
    ],
    enable2faKey: true,
    google2faSecret: '',
    createdAt: 1631643899000,
    updatedAt: 1662595682000,
  },
  {
    id: 161,
    username: 'tetsuya@phemex.com',
    mobile: '',
    email: 'tetsuya@phemex.com',
    status: 1,
    roleInfoList: [
      {
        id: 2,
        name: 'cs member',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 1,
        name: 'Super Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 139,
        name: '[TR] All View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 140,
        name: '[TR] Deposit Approve',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 43,
        name: 'Withdrawal_Request',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
    ],
    enable2faKey: true,
    google2faSecret: '',
    createdAt: 1638726752000,
    updatedAt: 1662595616000,
  },
  {
    id: 126,
    username: 'yumi.jiang',
    mobile: '',
    email: 'yumi.jiang@phemex.com',
    status: 1,
    roleInfoList: [
      {
        id: 2,
        name: 'cs member',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 8,
        name: 'ban user',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 13,
        name: 'CS_Deposit_Withdraw',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 59,
        name: 'P2P Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 73,
        name: 'P2P_Order_List',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 1,
        name: 'Super Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 120,
        name: 'Personal KYC Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 147,
        name: 'Deposit Slip Approve',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 139,
        name: '[TR] All View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 140,
        name: '[TR] Deposit Approve',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
    ],
    enable2faKey: true,
    google2faSecret: '',
    createdAt: 1628464667000,
    updatedAt: 1662595270000,
  },
  {
    id: 82,
    username: 'aaron',
    mobile: '',
    email: 'aaron.zhu@phemex.com',
    status: 1,
    roleInfoList: [
      {
        id: 2,
        name: 'cs member',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 8,
        name: 'ban user',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 13,
        name: 'CS_Deposit_Withdraw',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 59,
        name: 'P2P Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 73,
        name: 'P2P_Order_List',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 1,
        name: 'Super Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 120,
        name: 'Personal KYC Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 139,
        name: '[TR] All View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 140,
        name: '[TR] Deposit Approve',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 147,
        name: 'Deposit Slip Approve',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
    ],
    enable2faKey: true,
    google2faSecret: '',
    createdAt: 1615166547000,
    updatedAt: 1662574836000,
  },
  {
    id: 64,
    username: 'sam',
    mobile: '',
    email: 'sam.cheng@phemex.com',
    status: 1,
    roleInfoList: [
      {
        id: 2,
        name: 'cs member',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 8,
        name: 'ban user',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 13,
        name: 'CS_Deposit_Withdraw',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 21,
        name: 'cs big client',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 79,
        name: 'p2p-cs',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 1,
        name: 'Super Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 120,
        name: 'Personal KYC Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 139,
        name: '[TR] All View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 140,
        name: '[TR] Deposit Approve',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 148,
        name: 'Maker_Whitelist',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 59,
        name: 'P2P Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 73,
        name: 'P2P_Order_List',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 149,
        name: 'Add',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 150,
        name: 'Edit',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
    ],
    enable2faKey: true,
    google2faSecret: '',
    createdAt: 1608181760000,
    updatedAt: 1662440604000,
  },
  {
    id: 12,
    username: 'Travis',
    mobile: '13611655254',
    email: 'travis.chou@phemex.com',
    status: 1,
    roleInfoList: [
      {
        id: 2,
        name: 'cs member',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 8,
        name: 'ban user',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 13,
        name: 'CS_Deposit_Withdraw',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 59,
        name: 'P2P Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 73,
        name: 'P2P_Order_List',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 42,
        name: 'Deposit_And_Withdrawal',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 43,
        name: 'Withdrawal_Request',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 101,
        name: 'User_Recharge_Compensation_List',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 77,
        name: 'Airdrop_List',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 1,
        name: 'Super Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 112,
        name: 'Trade_Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 90,
        name: 'Coin_Info',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 91,
        name: 'Coin_Configuration',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 89,
        name: 'Coin_Basic_Info',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 120,
        name: 'Personal KYC Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 139,
        name: '[TR] All View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 140,
        name: '[TR] Deposit Approve',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
    ],
    enable2faKey: true,
    google2faSecret: '',
    createdAt: 1580787271000,
    updatedAt: 1662440587000,
  },
  {
    id: 28,
    username: 'zeben',
    mobile: '',
    email: 'zeben@phemex.com',
    status: 1,
    roleInfoList: [
      {
        id: 2,
        name: 'cs member',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 8,
        name: 'ban user',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 13,
        name: 'CS_Deposit_Withdraw',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 20,
        name: 'cs bonus issue',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 59,
        name: 'P2P Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 73,
        name: 'P2P_Order_List',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 43,
        name: 'Withdrawal_Request',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 1,
        name: 'Super Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 52,
        name: 'Withdrawal_Address_List',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 120,
        name: 'Personal KYC Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 139,
        name: '[TR] All View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 140,
        name: '[TR] Deposit Approve',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
    ],
    enable2faKey: true,
    google2faSecret: '',
    createdAt: 1587967253000,
    updatedAt: 1662440572000,
  },
  {
    id: 22,
    username: 'Kris',
    mobile: '',
    email: 'krystof.sedlon@phemex.com',
    status: 1,
    roleInfoList: [
      {
        id: 2,
        name: 'cs member',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 8,
        name: 'ban user',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 13,
        name: 'CS_Deposit_Withdraw',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 59,
        name: 'P2P Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 73,
        name: 'P2P_Order_List',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 1,
        name: 'Super Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 120,
        name: 'Personal KYC Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 139,
        name: '[TR] All View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 140,
        name: '[TR] Deposit Approve',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
    ],
    enable2faKey: true,
    google2faSecret: '',
    createdAt: 1585273239000,
    updatedAt: 1662440555000,
  },
  {
    id: 133,
    username: 'berkan.saracoglu',
    mobile: '',
    email: 'berkan.saracoglu@phemex.com',
    status: 1,
    roleInfoList: [
      {
        id: 2,
        name: 'cs member',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 138,
        name: '[TR] ADMIN',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 139,
        name: '[TR] All View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 140,
        name: '[TR] Deposit Approve',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
    ],
    enable2faKey: true,
    google2faSecret: '',
    createdAt: 1631643877000,
    updatedAt: 1661970812000,
  },
  {
    id: 137,
    username: 'jian.huang@cmexpro.com',
    mobile: '',
    email: 'jian.huang@cmexpro.com',
    status: 1,
    roleInfoList: [
      {
        id: 5,
        name: 'rd member',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 25,
        name: 'tech coin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 22,
        name: 'tech member',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 26,
        name: 'tech_airdrop_query',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 34,
        name: 'tech robot account transfer',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 80,
        name: 'Convert_Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 92,
        name: 'Convert_Dashboard',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 81,
        name: 'Convert_Configuration',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 139,
        name: '[TR] All View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 143,
        name: 'Spot Fee Promotion',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
    ],
    enable2faKey: true,
    google2faSecret: '',
    createdAt: 1632251846000,
    updatedAt: 1661820605000,
  },
  {
    id: 95,
    username: 'marco',
    mobile: '',
    email: 'marco.liu@phemex.com',
    status: 1,
    roleInfoList: [
      {
        id: 5,
        name: 'rd member',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 1,
        name: 'Super Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 33,
        name: 'SuperAdmin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 98,
        name: 'Guess_Price',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 86,
        name: 'Spot_Pair_Configuration',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 85,
        name: 'Spot_Pair_Detail',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 84,
        name: 'Contract_Pair_Configuration',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 83,
        name: 'Contract_Pair_Detail',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 138,
        name: '[TR] ADMIN',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 139,
        name: '[TR] All View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 144,
        name: 'Predict_Configuration',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 143,
        name: 'Spot Fee Promotion',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
    ],
    enable2faKey: true,
    google2faSecret: '',
    createdAt: 1618272771000,
    updatedAt: 1661820566000,
  },
  {
    id: 205,
    username: 'tangiz@phemex.com',
    mobile: '',
    email: 'tangiz@phemex.com',
    status: 1,
    roleInfoList: [
      {
        id: 2,
        name: 'cs member',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 20,
        name: 'cs bonus issue',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 138,
        name: '[TR] ADMIN',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 139,
        name: '[TR] All View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
    ],
    enable2faKey: true,
    google2faSecret: '',
    createdAt: 1646783328000,
    updatedAt: 1661499411000,
  },
  {
    id: 184,
    username: 'mcsherry@phemex.com',
    mobile: '',
    email: 'mcsherry@phemex.com',
    status: 1,
    roleInfoList: [
      {
        id: 2,
        name: 'cs member',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 138,
        name: '[TR] ADMIN',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 139,
        name: '[TR] All View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
    ],
    enable2faKey: true,
    google2faSecret: '',
    createdAt: 1643664509000,
    updatedAt: 1661499388000,
  },
  {
    id: 176,
    username: 'umut.yagiz@phemex.com',
    mobile: '',
    email: 'umut.yagiz@phemex.com',
    status: 1,
    roleInfoList: [
      {
        id: 2,
        name: 'cs member',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 20,
        name: 'cs bonus issue',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 138,
        name: '[TR] ADMIN',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 139,
        name: '[TR] All View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
    ],
    enable2faKey: true,
    google2faSecret: '',
    createdAt: 1641781661000,
    updatedAt: 1661499348000,
  },
  {
    id: 117,
    username: 'xingli.yan',
    mobile: '',
    email: 'xingli.yan@cmexpro.com',
    status: 1,
    roleInfoList: [
      {
        id: 18,
        name: 'customize',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 124,
        name: 'Privilege_Center_View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 139,
        name: '[TR] All View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 1,
        name: 'Super Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
    ],
    enable2faKey: true,
    google2faSecret: '',
    createdAt: 1626051883000,
    updatedAt: 1661135303000,
  },
  {
    id: 139,
    username: 'ayzecan.dogan',
    mobile: '',
    email: 'ayzecan.dogan@phemex.com',
    status: 1,
    roleInfoList: [
      {
        id: 2,
        name: 'cs member',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 59,
        name: 'P2P Management',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 73,
        name: 'P2P_Order_List',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 1,
        name: 'Super Admin',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 139,
        name: '[TR] All View',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: 140,
        name: '[TR] Deposit Approve',
        parentId: null,
        parentName: null,
        remark: null,
        createdAt: null,
        updatedAt: null,
      },
    ],
    enable2faKey: true,
    google2faSecret: '',
    createdAt: 1632866037000,
    updatedAt: 1660593374000,
  },
];
console.log(data.map((d) => d.email));
